"""Initial schema: chunks, documents, conversations, messages, citations.

Subsumes the former `001_chunks.sql`, which is deleted. Alembic owns every table
now — two schema tools on one database is how a staging box ends up with a column
production does not have.

Hand-written rather than autogenerated. `chunks.tsv` is a `GENERATED ALWAYS AS`
column and `chunks.embedding` is `vector(1536)`; neither round-trips cleanly
through autogenerate, and a revision that silently drops the generated clause
takes the lexical arm of retrieval with it.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import ARRAY, TSVECTOR

from alembic import context, op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

_STATUSES = ("pending", "answered", "refused", "needs_clarification", "failed")


def _existing_tables() -> set[str]:
    """What the target database already has.

    S3 provisioned `chunks` through the old `001_chunks.sql`, so a database that
    has been ingested against already holds it — with 220 rows and 220 paid-for
    embeddings. This revision adopts that table rather than recreating it; a
    fresh clone still gets the whole schema.

    Offline (`upgrade --sql`) there is no connection to inspect, so it renders
    the fresh-database path. That is also what keeps T-40 able to compare the
    full rendered schema against models.py.
    """
    if context.is_offline_mode():
        return set()
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    existing = _existing_tables()

    if "documents" not in existing:
        _create_documents()

    if "chunks" not in existing:
        _create_chunks()
    else:
        _adopt_chunks()

    if "conversations" not in existing:
        _create_conversations()
    if "messages" not in existing:
        _create_messages()
    if "citations" not in existing:
        _create_citations()


def _create_documents() -> None:
    op.create_table(
        "documents",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("product", sa.Text(), nullable=False),
        sa.Column("doc_role", sa.Text(), nullable=False),
        sa.Column("superseded", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("source_path", sa.Text()),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )


def _create_chunks() -> None:
    # Carried over from 001_chunks.sql. The per-document columns duplicate
    # `documents` on purpose: hybrid.py selects them by name inside a query whose
    # ranking constants were measured against the real index, and rewriting it to
    # save a join across 13 documents is not worth the risk at this scale.
    op.create_table(
        "chunks",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("document_id", sa.Text(), sa.ForeignKey("documents.id")),
        sa.Column("document_code", sa.Text(), nullable=False),
        sa.Column("document_title", sa.Text(), nullable=False),
        sa.Column("section", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("product", sa.Text(), nullable=False),
        sa.Column("doc_role", sa.Text(), nullable=False),
        sa.Column("chunk_kind", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("superseded", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("contains_pii", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("pii_kinds", ARRAY(sa.Text()), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("caption", sa.Text()),
        sa.Column("footnotes", ARRAY(sa.Text()), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("page_from", sa.Integer(), nullable=False),
        sa.Column("page_to", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(1536)),
        sa.Column(
            "tsv",
            TSVECTOR(),
            sa.Computed(
                "to_tsvector('portuguese', coalesce(section, '') || ' ' || text)",
                persisted=True,
            ),
        ),
    )
    op.create_index("chunks_tsv_gin", "chunks", ["tsv"], postgresql_using="gin")
    op.create_index("chunks_filters", "chunks", ["superseded", "product"])
    # No index on embedding: ~200 rows, exact scan beats HNSW. Revisit near 50k.


def _adopt_chunks() -> None:
    """Bring an S3-provisioned `chunks` under Alembic without touching its rows.

    Only the column this revision adds is applied. The 220 embeddings stay: they
    were paid for, and S3's recall@5 numbers were measured against them.
    """
    columns = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("chunks")}
    if "document_id" not in columns:
        op.add_column("chunks", sa.Column("document_id", sa.Text()))
        op.create_foreign_key(
            "chunks_document_id_fkey", "chunks", "documents", ["document_id"], ["id"]
        )


def _create_conversations() -> None:
    op.create_table(
        "conversations",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )


def _create_messages() -> None:
    op.create_table(
        "messages",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column(
            "conversation_id",
            sa.Text(),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("client_message_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(*_STATUSES, name="message_status"),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("answer_text", sa.Text()),
        sa.Column("error_code", sa.Text()),
        sa.Column("reason", sa.Text()),
        sa.Column("model", sa.Text(), nullable=False, server_default=""),
        sa.Column("prompt_version", sa.Text(), nullable=False, server_default=""),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_usd", sa.Numeric(10, 6), nullable=False, server_default="0"),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("completion_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cached_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("degraded", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        # Idempotency lives here, not in a process's memory. Two workers each hold
        # their own dict; they share this constraint.
        sa.UniqueConstraint(
            "conversation_id", "client_message_id", name="messages_client_idem"
        ),
    )
    op.create_index("messages_conversation_seq", "messages", ["conversation_id", "seq"])


def _create_citations() -> None:
    op.create_table(
        "citations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True),
        sa.Column(
            "message_id",
            sa.Text(),
            sa.ForeignKey("messages.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Text(), nullable=False),
        # Deliberately not a foreign key to chunks: a citation is a point-in-time
        # record decoupled from the current index, and an FK would block
        # `TRUNCATE chunks`, which is how a re-chunk after a parser change is done.
        sa.Column("chunk_id", sa.Text()),
        sa.Column("document_code", sa.Text(), nullable=False),
        sa.Column("document_title", sa.Text(), nullable=False),
        sa.Column("section", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.UniqueConstraint("message_id", "ordinal", name="citations_message_ordinal"),
    )
    op.create_index("citations_document", "citations", ["document_code", "version"])


def downgrade() -> None:
    op.drop_table("citations")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("chunks")
    op.drop_table("documents")
    sa.Enum(name="message_status").drop(op.get_bind(), checkfirst=True)
